#!/usr/bin/env node

// 3rd party
var debug = require('debug')('main'),
    program = require('commander'),
    request = require('request'),
    console = require('better-console');

var path = require('path');
var utility = require('./utility.js');

program
    .option('-t, --theme [theme_id]', 'work on theme. If theme_id omit, deal all themes. If don\'t have default theme, create one. Please avoid same name. [theme] not working now.')
    .option('-d, --domain-config', 'work on domanin config, if you want upload, you need have globe admin.')
    .option('-w, --widget', 'work on widget(not working now)')
    .option('-u, --user <account:password,[account:password]>', 'When you choose sync, you need enter two sets of account. If two set are the same you can put only one set.')
    // .option('-f, --force', 'Force update')
    .option('-p, --path <path>', 'Save file path, if omit, using ./');

program.parse(process.argv);

var task = {
    themeId: '',
    origPath: path.normalize(program.path || './'),
    path: '',
    target: {
        domain: program.args[0] || '',
        auth: {
            username: '',
            password: ''
        },
        cookie: ''
    },
    // Can switch between source and target.
    current: 'target'
};

task.path = task.origPath;

if (program.user) {
    var ac = program.user.split(',');
    var targetAc = ac[1];
    task.target.auth.username = targetAc ? targetAc.split(':')[0] : ac[0].split(':')[0];
    task.target.auth.password = targetAc ? targetAc.split(':')[1] : ac[0].split(':')[1];
} else {
    console.error('please enter you user acconut, use -u');
    return;
}

if (program.theme) {
    utility.uploadThemes(task);
}else if (program.domainConfig) {
    utility.uploadDomainConfig(task);
}else {
    utility.uploadThemes(task);
    utility.uploadDomainConfig(task);
}

